### ISSUE TITLE
"&" in URL will change to "&amp;" on slack.com

### ISSUE THREAD

**Issue by shokai** [shokai/hubot-rss-reader#27]
![image](https://cloud.githubusercontent.com/assets/34204/5843516/5bf94344-a1f0-11e4-9690-d28801743689.png)

```
hubot-rss-reader:rss-checker fetch https://www.facebook.com/feeds/page.php?format=rss20&amp;id=717064045041948
```

**Comment by patrys** [comment]
This bug is actually fixed in `hubot-slack` but the version was not yet released. I don't think decoding them the second time in your package is a good idea.

Try:

```
npm install --save https://github.com/slackhq/hubot-slack/tarball/master
```

**Comment by shokai** [comment]
ok, I will remove this commit.
