### ISSUE TITLE
add feeds silent

### ISSUE THREAD

**Issue by Jaglag** [shokai/hubot-rss-reader#34]
add feeds without the last 5 news feed posts.
You can see everything in log if its added correctly or not?

**Comment by shokai** [comment]
I have added this omitting entries, for Slack API's rate-limit.
I will add option to disable it.

**Comment by Jaglag** [comment]
Tyvm for fixxing all this stuff very nice plugin still using it!

**Comment by shokai** [comment]
set number of printing entries on `hubot add http://~~`

    % export HUBOT_RSS_LIMIT_ON_ADD=10


disable limit.

    % export HUBOT_RSS_LIMIT_ON_ADD=false
