### ISSUE TITLE
forgets links

### ISSUE THREAD

**Issue by yuukiw** [shokai/hubot-rss-reader#44]
I did register a link to the bot but he forgot it after a few minutes.

**Comment by shokai** [comment]
which hubot-brain is he using?
probably it is redis-brain (default brain)'s error.

**Comment by yuukiw** [comment]
I rebuilt the bot on basis of mongdb(?)  via npm commands.  But now I also discovered that he remembers the links as long as heroku doesn't do a restart. So is it somehow possible to hard code an url. I looked at the code myself and while I understand most of it in theory and would have an basic idea on how to to it but couldnt get it to work myself due lack of knowledge with js.
